openapi: 3.0.3
info:
  title: Materialize Cloud
  version: 0.1.0
servers:
- url: https://cloud.materialize.com
paths:
  /api/cloud-providers:
    get:
      description: List the cloud provider and regions
      operationId: cloudProvidersList
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SupportedCloudRegion'
                type: array
      security:
      - tokenAuth: []
      - {}
      tags:
      - cloud-providers
  /api/deployments:
    get:
      description: List the available deployments.
      operationId: deploymentsList
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Deployment'
                type: array
      security:
      - tokenAuth: []
      tags:
      - deployments
    post:
      description: Create a new deployment.
      operationId: deploymentsCreate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeploymentRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
      security:
      - tokenAuth: []
      tags:
      - deployments
  /api/deployments/{id}:
    delete:
      description: Destroy a deployment.
      operationId: deploymentsDestroy
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No response body
      security:
      - tokenAuth: []
      tags:
      - deployments
    get:
      description: Fetch details about a single deployment.
      operationId: deploymentsRetrieve
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
      security:
      - tokenAuth: []
      tags:
      - deployments
    patch:
      description: Partially update a deployment.
      operationId: deploymentsPartialUpdate
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedDeploymentUpdateRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
      security:
      - tokenAuth: []
      tags:
      - deployments
  /api/deployments/{id}/certs:
    get:
      description: |-
        Retrieve a TLS certificate bundle for a deployment.

        The TLS certificate bundle is a ZIP file containing PEM and DER
        formatted keys that permit authenticating to the deployment as the
        `materialize` user.
      operationId: deploymentsCertsRetrieve
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/zip:
              schema:
                format: binary
                type: string
      security:
      - tokenAuth: []
      tags:
      - deployments
  /api/deployments/{id}/changes:
    get:
      operationId: deploymentsChangesList
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/HistoricalDeploymentDelta'
                type: array
      security:
      - tokenAuth: []
      tags:
      - deployments
  /api/deployments/{id}/ip:
    get:
      operationId: deploymentsIpRetrieve
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: ipv4
                type: string
      security:
      - tokenAuth: []
      tags:
      - deployments
  /api/deployments/{id}/logs:
    get:
      description: Retrieve the logs for a deployment.
      operationId: deploymentsLogsRetrieve
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: previous
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
      security:
      - tokenAuth: []
      tags:
      - deployments
  /api/deployments/{id}/metrics/cpu/{period}:
    get:
      description: Retrieve cpu line graph as a list of tuples (timestamps / utilization
        in %)) for a deployment.
      operationId: deploymentsMetricsCpuRetrieve
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: period
        required: true
        schema:
          type: number
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrometheusMetrics'
      security:
      - tokenAuth: []
      tags:
      - deployments
  /api/deployments/{id}/metrics/memory/{period}:
    get:
      description: Retrieve memory line graph data (as a list of tuples (timestamps
        / utilization in %)) for a deployment.
      operationId: deploymentsMetricsMemoryRetrieve
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: period
        required: true
        schema:
          type: number
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrometheusMetrics'
      security:
      - tokenAuth: []
      tags:
      - deployments
  /api/deployments/{id}/secrets:
    get:
      description: List all customer defined secrets for the deployment
      operationId: deploymentsSecretsList
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
      - tokenAuth: []
      tags:
      - deployments
  /api/deployments/{id}/secrets/{secret}:
    delete:
      description: Delete a customer defined secret from the deployment
      operationId: deploymentsSecretsDestroy
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: secret
        required: true
        schema:
          pattern: ^[^/]+$
          type: string
        style: simple
      responses:
        "204":
          description: No response body
      security:
      - tokenAuth: []
      tags:
      - deployments
    post:
      description: Insert/update a customer defined secret in the deployment
      operationId: deploymentsSecretsCreate
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: secret
        required: true
        schema:
          pattern: ^[^/]+$
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        "204":
          description: No response body
      security:
      - tokenAuth: []
      tags:
      - deployments
  /api/deployments/{id}/tailscale_logs:
    get:
      description: Retrieve the logs for a Tailscale container.
      operationId: deploymentsTailscaleLogsRetrieve
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: previous
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
      security:
      - tokenAuth: []
      tags:
      - deployments
  /api/health:
    get:
      description: |-
        Basic health check endpoint.

        This endpoint always returns 200 OK. It is intended for use by load
        balancers and such that need a basic indication as to whether the server is
        live.
      operationId: healthRetrieve
      responses:
        "200":
          description: No response body
      security:
      - tokenAuth: []
      - {}
      tags:
      - health
  /api/mz-versions:
    get:
      description: |-
        List the versions of Materialize known to Materialize Cloud.

        Versions are listed in order from oldest to newest.
      operationId: mzVersionsList
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
      - tokenAuth: []
      - {}
      tags:
      - mz-versions
  /api/mz-versions/latest:
    get:
      description: Returns the latest version of Materialize.
      operationId: mzVersionsLatestRetrieve
      parameters:
      - explode: true
        in: query
        name: track
        required: false
        schema:
          default: stable
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
      security:
      - tokenAuth: []
      - {}
      tags:
      - mz-versions
  /api/organizations/{id}:
    get:
      description: Fetch details about a single organization.
      operationId: organizationsRetrieve
      parameters:
      - description: A UUID string identifying this organization.
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
      security:
      - tokenAuth: []
      tags:
      - organizations
  /api/regions/{providerName}:
    get:
      operationId: regionsList
      parameters:
      - explode: false
        in: path
        name: providerName
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SupportedCloudRegion'
                type: array
      security:
      - tokenAuth: []
      - {}
      tags:
      - regions
  /api/schema:
    get:
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      operationId: schemaRetrieve
      parameters:
      - explode: true
        in: query
        name: format
        required: false
        schema:
          enum:
          - json
          - yaml
          type: string
        style: form
      responses:
        "200":
          content:
            application/vnd.oai.openapi:
              schema:
                additionalProperties: {}
                type: object
            application/yaml:
              schema:
                additionalProperties: {}
                type: object
            application/vnd.oai.openapi+json:
              schema:
                additionalProperties: {}
                type: object
            application/json:
              schema:
                additionalProperties: {}
                type: object
      security:
      - tokenAuth: []
      - {}
      tags:
      - schema
components:
  schemas:
    Deployment:
      example:
        flaggedForUpdate: true
        flaggedForDeletion: true
        clusterId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        mzVersion: mzVersion
        enableTailscale: false
        cloudProviderRegion:
          region: region
        hostname: hostname
        materializedExtraArgs:
        - materializedExtraArgs
        - materializedExtraArgs
        size: ""
        tlsAuthority: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        catalogRestoreMode: false
        organization: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        name: name
        storageMb: 80174
        releaseTrack: ""
        id: id
        disableUserIndexes: false
        status: status
      properties:
        id:
          readOnly: true
          type: string
        organization:
          format: uuid
          readOnly: true
          type: string
        tlsAuthority:
          format: uuid
          nullable: true
          readOnly: true
          type: string
        name:
          type: string
        hostname:
          nullable: true
          readOnly: true
          type: string
        flaggedForDeletion:
          readOnly: true
          type: boolean
        flaggedForUpdate:
          readOnly: true
          type: boolean
        catalogRestoreMode:
          default: false
          type: boolean
        size:
          allOf:
          - $ref: '#/components/schemas/DeploymentSizeEnum'
        storageMb:
          default: 100
          maximum: 1000000
          minimum: 100
          type: integer
        disableUserIndexes:
          default: false
          type: boolean
        materializedExtraArgs:
          items:
            maxLength: 4096
            type: string
          title: Extra materialized arguments
          type: array
        clusterId:
          format: uuid
          nullable: true
          readOnly: true
          type: string
        mzVersion:
          type: string
        releaseTrack:
          allOf:
          - $ref: '#/components/schemas/ReleaseTrackEnum'
        status:
          readOnly: true
          type: string
        enableTailscale:
          default: false
          type: boolean
        cloudProviderRegion:
          $ref: '#/components/schemas/SupportedCloudRegion'
      required:
      - catalogRestoreMode
      - cloudProviderRegion
      - clusterId
      - disableUserIndexes
      - enableTailscale
      - flaggedForDeletion
      - flaggedForUpdate
      - hostname
      - id
      - materializedExtraArgs
      - mzVersion
      - name
      - organization
      - releaseTrack
      - size
      - status
      - storageMb
      - tlsAuthority
      type: object
    DeploymentRequest:
      example:
        materializedExtraArgs:
        - materializedExtraArgs
        - materializedExtraArgs
        size: ""
        catalogRestoreMode: false
        name: name
        storageMb: 80174
        releaseTrack: ""
        disableUserIndexes: false
        mzVersion: mzVersion
        enableTailscale: false
        tailscaleAuthKey: tailscaleAuthKey
        cloudProviderRegion:
          region: region
      properties:
        name:
          minLength: 1
          type: string
        catalogRestoreMode:
          default: false
          type: boolean
        size:
          allOf:
          - $ref: '#/components/schemas/DeploymentSizeEnum'
        storageMb:
          default: 100
          maximum: 1000000
          minimum: 100
          type: integer
        disableUserIndexes:
          default: false
          type: boolean
        materializedExtraArgs:
          items:
            maxLength: 4096
            minLength: 1
            type: string
          title: Extra materialized arguments
          type: array
        mzVersion:
          minLength: 1
          type: string
        releaseTrack:
          allOf:
          - $ref: '#/components/schemas/ReleaseTrackEnum'
        enableTailscale:
          default: false
          type: boolean
        tailscaleAuthKey:
          minLength: 1
          type: string
          writeOnly: true
        cloudProviderRegion:
          $ref: '#/components/schemas/SupportedCloudRegionRequest'
      required:
      - cloudProviderRegion
      type: object
    DeploymentSizeEnum:
      enum:
      - XS
      - S
      - M
      - L
      - XL
      type: string
    HistoricalDeploymentChange:
      example:
        flaggedForUpdate: ""
        hostname: ""
        materializedExtraArgs: ""
        flaggedForDeletion: ""
        size: ""
        catalogRestoreMode: ""
        name: ""
        disableUserIndexes: ""
        clusterId: ""
        mzVersion: ""
        enableTailscale: ""
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/ModifiedString'
          readOnly: true
        hostname:
          allOf:
          - $ref: '#/components/schemas/ModifiedString'
          readOnly: true
        flaggedForDeletion:
          allOf:
          - $ref: '#/components/schemas/ModifiedBoolean'
          readOnly: true
        flaggedForUpdate:
          allOf:
          - $ref: '#/components/schemas/ModifiedBoolean'
          readOnly: true
        catalogRestoreMode:
          allOf:
          - $ref: '#/components/schemas/ModifiedBoolean'
          readOnly: true
        size:
          allOf:
          - $ref: '#/components/schemas/ModifiedSize'
          readOnly: true
        disableUserIndexes:
          allOf:
          - $ref: '#/components/schemas/ModifiedBoolean'
          readOnly: true
        materializedExtraArgs:
          allOf:
          - $ref: '#/components/schemas/ModifiedStringList'
          readOnly: true
        clusterId:
          allOf:
          - $ref: '#/components/schemas/ModifiedString'
          readOnly: true
        mzVersion:
          allOf:
          - $ref: '#/components/schemas/ModifiedString'
          readOnly: true
        enableTailscale:
          allOf:
          - $ref: '#/components/schemas/ModifiedBoolean'
          readOnly: true
      type: object
    HistoricalDeploymentDelta:
      example:
        metadata:
          date: 2000-01-23T04:56:07.000+00:00
          user: user
          operation: ""
        changes:
          flaggedForUpdate: ""
          hostname: ""
          materializedExtraArgs: ""
          flaggedForDeletion: ""
          size: ""
          catalogRestoreMode: ""
          name: ""
          disableUserIndexes: ""
          clusterId: ""
          mzVersion: ""
          enableTailscale: ""
      properties:
        changes:
          $ref: '#/components/schemas/HistoricalDeploymentChange'
        metadata:
          $ref: '#/components/schemas/HistoricalDeploymentMetadata'
      required:
      - changes
      - metadata
      type: object
    HistoricalDeploymentMetadata:
      example:
        date: 2000-01-23T04:56:07.000+00:00
        user: user
        operation: ""
      properties:
        date:
          format: date-time
          readOnly: true
          type: string
        user:
          readOnly: true
          type: string
        operation:
          allOf:
          - $ref: '#/components/schemas/OperationEnum'
          readOnly: true
      required:
      - date
      - operation
      - user
      type: object
    ModifiedBoolean:
      properties:
        old:
          nullable: true
          type: boolean
        new:
          nullable: true
          type: boolean
      required:
      - new
      - old
      type: object
    ModifiedSize:
      properties:
        old:
          $ref: '#/components/schemas/DeploymentSizeEnum'
        new:
          $ref: '#/components/schemas/DeploymentSizeEnum'
      required:
      - new
      - old
      type: object
    ModifiedString:
      properties:
        old:
          nullable: true
          type: string
        new:
          nullable: true
          type: string
      required:
      - new
      - old
      type: object
    ModifiedStringList:
      properties:
        old:
          items:
            nullable: true
            type: string
          type: array
        new:
          items:
            nullable: true
            type: string
          type: array
      required:
      - new
      - old
      type: object
    OperationEnum:
      enum:
      - CREATE
      - UPDATE
      - DELETE
      type: string
    Organization:
      example:
        deploymentLimit: 0
        trialExpiresAt: 2000-01-23T04:56:07.000+00:00
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          format: uuid
          readOnly: true
          type: string
        deploymentLimit:
          readOnly: true
          type: integer
        trialExpiresAt:
          description: When this organization's trial period expires. If empty, the
            organization is on an enterprise plan.
          format: date-time
          nullable: true
          readOnly: true
          type: string
      required:
      - deploymentLimit
      - id
      - trialExpiresAt
      type: object
    PatchedDeploymentUpdateRequest:
      example:
        materializedExtraArgs:
        - materializedExtraArgs
        - materializedExtraArgs
        size: ""
        catalogRestoreMode: false
        name: name
        storageMb: 80174
        releaseTrack: ""
        disableUserIndexes: false
        mzVersion: mzVersion
        enableTailscale: false
        tailscaleAuthKey: tailscaleAuthKey
      properties:
        name:
          minLength: 1
          type: string
        catalogRestoreMode:
          default: false
          type: boolean
        size:
          allOf:
          - $ref: '#/components/schemas/DeploymentSizeEnum'
        storageMb:
          default: 100
          maximum: 1000000
          minimum: 100
          type: integer
        disableUserIndexes:
          default: false
          type: boolean
        materializedExtraArgs:
          items:
            maxLength: 4096
            minLength: 1
            type: string
          title: Extra materialized arguments
          type: array
        mzVersion:
          minLength: 1
          type: string
        releaseTrack:
          allOf:
          - $ref: '#/components/schemas/ReleaseTrackEnum'
        enableTailscale:
          default: false
          type: boolean
        tailscaleAuthKey:
          minLength: 1
          type: string
          writeOnly: true
      type: object
    PrometheusMetric:
      example:
        values:
        - - values
          - values
        - - values
          - values
        name: name
      properties:
        name:
          type: string
        values:
          items:
            items:
              type: string
            type: array
          type: array
      required:
      - name
      - values
      type: object
    PrometheusMetrics:
      description: Serializer for the prometheus metrics.
      example:
        metrics:
        - values:
          - - values
            - values
          - - values
            - values
          name: name
        - values:
          - - values
            - values
          - - values
            - values
          name: name
      properties:
        metrics:
          items:
            $ref: '#/components/schemas/PrometheusMetric'
          type: array
      required:
      - metrics
      type: object
    ProviderEnum:
      enum:
      - AWS
      - local
      type: string
    ReleaseTrackEnum:
      enum:
      - canary
      - stable
      type: string
    SupportedCloudRegion:
      example:
        region: region
      properties:
        provider:
          $ref: '#/components/schemas/ProviderEnum'
        region:
          type: string
      required:
      - provider
      - region
      type: object
    SupportedCloudRegionRequest:
      example:
        region: region
      properties:
        provider:
          $ref: '#/components/schemas/ProviderEnum'
        region:
          minLength: 1
          type: string
      required:
      - provider
      - region
      type: object
  securitySchemes:
    tokenAuth:
      scheme: bearer
      type: http
